In [6]:
import numpy as np
import cv2
import glob


In [ ]:
def crop_and_resize(img, bound, size):
    
    xmin, ymin, xmax, ymax = bound
    w, h = size
    
    img_crop = img[ymin:ymax,xmin:xmax]
    #cv2.resize(img,None,fx=2, fy=2, interpolation = cv2.INTER_CUBIC)
    img_resized = cv2.resize(img_crop,(w, h), interpolation = cv2.INTER_CUBIC)
    return img_resized



In [32]:
path = 'dataset-master\\JPEGImages\\'
images = glob.glob(path + '*.jpg')

RBC_arr = []
#read images and make each into an array
for img in images:
    RBC_this = cv2.imread(img)
    #RBC_this = crop_and_resize(RBC_this, )
    RBC_this = np.reshape(RBC_this, -1)
    RBC_arr.append(RBC_this)
    
RBC_arr = np.asarray(RBC_arr)
RBC_mean = np.mean(RBC_arr, axis = 1)[np.newaxis]
RBC_centered = RBC_arr - RBC_mean.T
RBC_norm = np.linalg.norm(RBC_centered, axis = 1)[np.newaxis]
RBC_normalized = RBC_centered/RBC_norm.T


In [33]:
U, S, V = np.linalg.svd(RBC_normalized)

MemoryError: 

In [34]:
print(RBC_normalized.shape)

(366, 921600)


In [31]:
RBC_norm = np.linalg.norm(RBC_centered, axis = 1)[np.newaxis]
RBC_normalized = RBC_centered/RBC_norm.T

ValueError: operands could not be broadcast together with shapes (366,921600) (1,366) 

In [26]:
len(RBC_arr)
A = [[[1,2,3],[2,3,2],[3,4,3]],[[11,12,13],[12,13,12],[13,14,13]]]
A_vec = np.reshape(A, -1)  
B_vec = np.flip(A_vec)
A_centered = np.mean(np.asarray([A_vec, B_vec]), axis = 0)
print(A_centered)

[7. 8. 8. 7. 8. 7. 8. 8. 7. 7. 8. 8. 7. 8. 7. 8. 8. 7.]


In [12]:
print(RBC_arr[0])

[[[143 154 176]
  [143 154 176]
  [145 153 176]
  ...
  [203 197 190]
  [201 195 188]
  [199 193 186]]

 [[143 154 176]
  [143 154 176]
  [145 153 176]
  ...
  [203 197 190]
  [201 195 188]
  [199 193 186]]

 [[141 155 174]
  [141 155 174]
  [143 154 174]
  ...
  [201 198 190]
  [199 196 188]
  [197 194 186]]

 ...

 [[206 205 207]
  [201 203 204]
  [197 198 202]
  ...
  [185 124 162]
  [191 125 166]
  [197 131 172]]

 [[209 206 208]
  [204 203 205]
  [198 197 201]
  ...
  [184 121 161]
  [191 123 164]
  [196 128 169]]

 [[210 207 209]
  [206 203 205]
  [197 196 200]
  ...
  [183 120 160]
  [190 122 163]
  [197 127 168]]]


In [23]:
img = RBC_arr[0]

def crop_and_resize(img, bound, size):
    
    xmin, ymin, xmax, ymax = bound
    w, h = size
    
    img_crop = img[ymin:ymax,xmin:xmax]
    #cv2.resize(img,None,fx=2, fy=2, interpolation = cv2.INTER_CUBIC)
    img_resized = cv2.resize(img_crop,(w, h), interpolation = cv2.INTER_CUBIC)
    return img_resized
    
img_resized = crop_and_resize(img, (100, 50, 250, 200), (100, 100))
cv2.imshow('img', img_resized)
cv2.waitKey(0)
cv2.destroyAllWindows()